services:
  app:
    image: "${APP_IMAGE:-catalog_app:latest}"
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 80
    environment:
      - PYTHONPATH=/app
    ports:
      - 9000:80
    depends_on:
      - db
    volumes:
      - .:/app

  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    container_name: telegram_bot
    depends_on:
      - db
      - app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./:/app

  db:
    image: postgres:16
    container_name: pathway_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    ports:
      - "${POSTGRES_PORT}:5434"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db