version: "3.8"

services:
  app:
    image: "${APP_IMAGE:-catalog_app:latest}"
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 80
    ports:
      - 9000:80
    depends_on:
      - db
    volumes:
      - ./:/src

  db:
    image: postgres
    container_name: pathway_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    ports:
      - "${POSTGRES_PORT}:5434"