[tool.poetry]
name = "pathway"
version = "0.1.0"
description = ""
authors = ["alexey <aleksei.bakeev@strana.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
folium = "^0.19.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
